line-length = 100
target-version = "py312"
exclude = ["uv.lock"]

[lint]
extend-select = ["I", "UP", "B", "C4", "DTZ", "TCH"]
ignore = []

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
docstring-code-format = true
